language: node_js
node_js:
  - "12"

install: 
  - npm install -g serverless
  - travis_retry npm install

script:
  - export NODE_OPTIONS=--max_old_space_size=8192
  - serverless deploy --verbose

environments:
  - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
